services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/taskdb
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        # A API agora espera o 'db' estar "saudável" antes de iniciar
        condition: service_healthy

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # A verificação de saúde: o Docker vai rodar 'pg_isready' repetidamente
    # até que o banco de dados responda que está pronto.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: