### Arquivo de Requisições para a Task Manager API

# Define a variável de host para o nosso ambiente local
@host = http://localhost:3000

# Define uma variável para o token JWT. Cole o token aqui após fazer o login.
@token = c-dAuDFQrdjS3hezqxDTNgW7AOlYk

######################################################
# 1. REGISTRAR UM USUÁRIO DE TESTE
###
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "Usuario de Teste",
  "email": "teste@email.com",
  "password": "123"
}

######################################################
# 2. FAZER LOGIN PARA OBTER O TOKEN
###
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123"
}

######################################################
# 3. LISTAR TODAS AS MINHAS TAREFAS (REQUER TOKEN)
###
GET {{host}}/tasks
Authorization: Bearer {{token}}


######################################################
# 4. CRIAR UMA NOVA TAREFA (REQUER TOKEN)
###
POST {{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Aprender a testar APIs",
  "description": "Usar o REST Client para verificar os endpoints"
}


######################################################
# 5. ATUALIZAR UMA TAREFA (REQUER TOKEN)
# Lembre-se de substituir o '1' pelo ID da tarefa que você quer editar
###
PATCH {{host}}/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Aprender a testar APIs (Atualizado)",
  "status": "done"
}


######################################################
# 6. DELETAR UMA TAREFA (REQUER TOKEN)
# Lembre-se de substituir o '1' pelo ID da tarefa que você quer deletar
###
DELETE {{host}}/tasks/1
Authorization: Bearer {{token}}